In [209]:
import os
import pandas as pd
import numpy as np
from datetime import datetime
from dateutil import tz

In [210]:
data_filepath = "C:/Users/glius/Google Drive/HOPE/data"
def read_data(option, data_filepath):
  raw_data = pd.DataFrame()
  patient_names = os.listdir(data_filepath)
  for patient_name in patient_names:
    data_folder = data_filepath + "/" + patient_name +  "/" + option
    if os.path.exists(data_folder):
      data_files = os.listdir(data_folder)
      for data_file in data_files: 
        dest_path = data_folder + "/" + data_file
        hour_data = pd.read_csv(dest_path)
        hour_data["patient"] = patient_name
        from_zone = tz.gettz('UTC')
        to_zone = tz.gettz('America/New_York')
        UTC = [datetime.strptime(i, '%Y-%m-%dT%H:%M:%S.%f') for i in hour_data['UTC time']]
        EST = [i.replace(tzinfo=from_zone).astimezone(to_zone) for i in UTC]
        hour_data["date"] = [i.date() for i in EST]
        raw_data = raw_data.append(hour_data)
  return raw_data

In [197]:
raw_calls = read_data("calls",data_filepath)
raw_texts = read_data("texts",data_filepath)

In [198]:
raw_calls.head(10)

,timestamp,UTC time,hashed phone number,call type,duration in seconds,patient,date
0,1516467914045,2018-01-20T17:05:14.045,N74DxyHmc6ZmOvXE61tzG4jFA4foeJmz_suytao9TcE=,Outgoing Call,15,1s5wlcm6,2018-01-20
1,1516468526474,2018-01-20T17:15:26.474,s6USBgpv5j5zlcuQM8_0mcaCpHspYDihZkmuDzgPgdY=,Outgoing Call,0,1s5wlcm6,2018-01-20
0,1516488243965,2018-01-20T22:44:03.965,bgBv1VVeep-UaH9xYeOcbEvvcZat3-6SHRFhkAyaVCc=,Outgoing Call,331,1s5wlcm6,2018-01-20
1,1516488586304,2018-01-20T22:49:46.304,bgBv1VVeep-UaH9xYeOcbEvvcZat3-6SHRFhkAyaVCc=,Outgoing Call,0,1s5wlcm6,2018-01-20
2,1516488598435,2018-01-20T22:49:58.435,bgBv1VVeep-UaH9xYeOcbEvvcZat3-6SHRFhkAyaVCc=,Outgoing Call,286,1s5wlcm6,2018-01-20
0,1516561953201,2018-01-21T19:12:33.201,4OyQsWBtcXanF9-rHWXxHA-s4Chvb8ek3ZoomTbv1dc=,Incoming Call,9,1s5wlcm6,2018-01-21
0,1517001631852,2018-01-26T21:20:31.852,TDWhMLvHxT0eeh1XDwg_kkIeqmRtRAoWTrvq1Fs9ESg=,Incoming Call,33,1s5wlcm6,2018-01-26
0,1517268142086,2018-01-29T23:22:22.086,3KbntH6hlCMqNYgiMpVAP4tcPV66SOTF6-WgkKK47Ok=,Incoming Call,1285,1s5wlcm6,2018-01-29
0,1517854542566,2018-02-05T18:15:42.566,bgBv1VVeep-UaH9xYeOcbEvvcZat3-6SHRFhkAyaVCc=,Outgoing Call,302,1s5wlcm6,2018-02-05
1,1517855599948,2018-02-05T18:33:19.948,bgBv1VVeep-UaH9xYeOcbEvvcZat3-6SHRFhkAyaVCc=,Outgoing Call,222,1s5wlcm6,2018-02-05

In [199]:
raw_texts.head(10)

,timestamp,UTC time,hashed phone number,sent vs received,message length,time sent,patient,date
0,1519419566755,2018-02-23T20:59:26.755,qF3BDBN3I8PDZzb3USUf2tOFEpBWrX-FTFaySChogxc=,received SMS,89,1.519392e+12,1s5wlcm6,2018-02-23
0,1519575163320,2018-02-25T16:12:43.320,Nw0EV3t_D2BgUs4rstRUbaLxkNUQRFMPLhhMo3p3vbU=,received SMS,153,1.519575e+12,1s5wlcm6,2018-02-25
1,1519575163327,2018-02-25T16:12:43.327,Nw0EV3t_D2BgUs4rstRUbaLxkNUQRFMPLhhMo3p3vbU=,received SMS,32,1.519575e+12,1s5wlcm6,2018-02-25
0,1521657216665,2018-03-21T18:33:36.665,cCmWGIaZw6Y5_tzCm5pUS4XpR6yWIJm1yd16SHITvWc=,received SMS,153,1.521657e+12,1s5wlcm6,2018-03-21
1,1521657216670,2018-03-21T18:33:36.670,cCmWGIaZw6Y5_tzCm5pUS4XpR6yWIJm1yd16SHITvWc=,received SMS,10,1.521657e+12,1s5wlcm6,2018-03-21
0,1523915116943,2018-04-16T21:45:16.943,null_data,received SMS,42,1.523915e+12,1s5wlcm6,2018-04-16
0,1524520964652,2018-04-23T22:02:44.652,JtIoZj8TqIWSoS0Wz5WHyqsDiLJi1tnxJu1i-TM6ypQ=,received SMS,156,1.524521e+12,1s5wlcm6,2018-04-23
0,1524752228941,2018-04-26T14:17:08.941,AnKVzUfCvhih9xRKwIzbFCsa9Qqz0zMGDvBD1v55WPo=,received SMS,142,1.524752e+12,1s5wlcm6,2018-04-26
1,1524752319808,2018-04-26T14:18:39.808,AnKVzUfCvhih9xRKwIzbFCsa9Qqz0zMGDvBD1v55WPo=,sent SMS,3,NaN,1s5wlcm6,2018-04-26
2,1524752325211,2018-04-26T14:18:45.211,AnKVzUfCvhih9xRKwIzbFCsa9Qqz0zMGDvBD1v55WPo=,sent SMS,3,NaN,1s5wlcm6,2018-04-26

In [200]:
## Compute statistics from the call data
raw_calls['duration in seconds'] = raw_calls['duration in seconds'].fillna(0.0).astype(int)
raw_calls['duration in minutes'] = raw_calls['duration in seconds']/60

summary_calls = raw_calls.groupby(["patient","date","call type"]).agg(
    {
        'timestamp': "count",
        'hashed phone number': "nunique",
        'duration in minutes': ["sum","mean"]
    }
)
calls_stats = summary_calls.unstack()
calls_stats = calls_stats.fillna(0.0)
calls_stats['id'] = [list(calls_stats.index)[i][0] for i in range(calls_stats.shape[0])]
calls_stats['date'] = [list(calls_stats.index)[i][1] for i in range(calls_stats.shape[0])]
calls_stats.columns = ['num of in calls','num of missed calls','num of out calls',
                       'num of in phones','num of missed phones','num of out phones',
                       'total len of in calls','total len of missed calls','total len of out calls',
                       'mean len of in calls','mean len of missed calls','mean len of out calls',
                       'id','date']
new_calls = calls_stats
calls_stats = pd.DataFrame(columns = list(calls_stats.columns))
for i in calls_stats.columns:
  calls_stats[i] = list(new_calls[i])
del new_calls
calls_stats.head(10)

,num of in calls,num of missed calls,num of out calls,num of in phones,num of missed phones,num of out phones,total len of in calls,total len of missed calls,total len of out calls,mean len of in calls,mean len of missed calls,mean len of out calls,id,date
0,0.0,0.0,5.0,0.0,0.0,3.0,0.000000,0.0,10.533333,0.000000,0.0,2.106667,1s5wlcm6,2018-01-20
1,1.0,0.0,0.0,1.0,0.0,0.0,0.150000,0.0,0.000000,0.150000,0.0,0.000000,1s5wlcm6,2018-01-21
2,1.0,0.0,0.0,1.0,0.0,0.0,0.550000,0.0,0.000000,0.550000,0.0,0.000000,1s5wlcm6,2018-01-26
3,1.0,0.0,0.0,1.0,0.0,0.0,21.416667,0.0,0.000000,21.416667,0.0,0.000000,1s5wlcm6,2018-01-29
4,0.0,0.0,2.0,0.0,0.0,1.0,0.000000,0.0,8.733333,0.000000,0.0,4.366667,1s5wlcm6,2018-02-05
5,0.0,1.0,1.0,0.0,1.0,1.0,0.000000,0.0,0.183333,0.000000,0.0,0.183333,1s5wlcm6,2018-02-11
6,0.0,0.0,3.0,0.0,0.0,3.0,0.000000,0.0,1.400000,0.000000,0.0,0.466667,1s5wlcm6,2018-02-12
7,0.0,0.0,2.0,0.0,0.0,2.0,0.000000,0.0,0.916667,0.000000,0.0,0.458333,1s5wlcm6,2018-02-16
8,0.0,0.0,3.0,0.0,0.0,3.0,0.000000,0.0,85.783333,0.000000,0.0,28.594444,1s5wlcm6,2018-02-17
9,0.0,0.0,1.0,0.0,0.0,1.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,1s5wlcm6,2018-02-25

In [201]:
## Compute statistics from the text data
raw_texts.loc[raw_texts["sent vs received"] == "sent MMS", "sent vs received"] = "sent SMS"
raw_texts.loc[raw_texts["sent vs received"] == "received MMS", "sent vs received"] = "received SMS"
raw_texts.loc[raw_texts["message length"] == "MMS", "message length"] = 0
raw_texts['message length'] = raw_texts['message length'].fillna(0.0).astype(int)

summary_texts = raw_texts.groupby(["patient","date","sent vs received"]).agg(
    {
        'timestamp': "count",
        'hashed phone number': "nunique",
        'message length': ["sum","mean"]
    }
)
texts_stats = summary_texts.unstack()
texts_stats = texts_stats.fillna(0.0)
texts_stats['id'] = [list(texts_stats.index)[i][0] for i in range(texts_stats.shape[0])]
texts_stats['date'] = [list(texts_stats.index)[i][1] for i in range(texts_stats.shape[0])]

texts_stats.columns = ['num of received sms','num of sent sms','num of received phone',
                       'num of sent phone','total len of received sms','total len of sent sms','mean len of received sms',
                      'mean len of sent sms','id','date']
new_texts = texts_stats
texts_stats = pd.DataFrame(columns = list(texts_stats.columns))
for i in texts_stats.columns:
  texts_stats[i] = list(new_texts[i])
del new_texts
texts_stats.head(10)

,num of received sms,num of sent sms,num of received phone,num of sent phone,total len of received sms,total len of sent sms,mean len of received sms,mean len of sent sms,id,date
0,1.0,0.0,1.0,0.0,89.0,0.0,89.000000,0.0000,1s5wlcm6,2018-02-23
1,2.0,0.0,1.0,0.0,185.0,0.0,92.500000,0.0000,1s5wlcm6,2018-02-25
2,2.0,0.0,1.0,0.0,163.0,0.0,81.500000,0.0000,1s5wlcm6,2018-03-21
3,1.0,0.0,1.0,0.0,42.0,0.0,42.000000,0.0000,1s5wlcm6,2018-04-16
4,1.0,0.0,1.0,0.0,156.0,0.0,156.000000,0.0000,1s5wlcm6,2018-04-23
5,1.0,2.0,1.0,1.0,142.0,6.0,142.000000,3.0000,1s5wlcm6,2018-04-26
6,9.0,8.0,3.0,5.0,456.0,565.0,50.666667,70.6250,3j2fdbb,2018-09-13
7,5.0,3.0,3.0,2.0,178.0,153.0,35.600000,51.0000,3j2fdbb,2018-09-14
8,1.0,1.0,1.0,1.0,29.0,66.0,29.000000,66.0000,3j2fdbb,2018-09-15
9,20.0,16.0,3.0,2.0,979.0,445.0,48.950000,27.8125,3j2fdbb,2018-09-16

In [235]:
final_output = pd.DataFrame()
patient_names = os.listdir(data_filepath)
for patient_name in patient_names:
  ## In this loop, we do the following:
  ## Get first and last date with the app on phone. These dates will be used as the time range in the subject's plots
  ## Some dates between the first and last date may not be in the summarized data frame because there were no incoming,
  ## outgoing, or missed calls on that date. We will add those dates with 0's for all the call/text statistics
  sub_calls = calls_stats.loc[list(calls_stats["id"] == patient_name),:]
  sub_texts = texts_stats.loc[list(texts_stats["id"] == patient_name),:]
  for j in range(2):
    if j==0:
      sub_data = sub_calls
    if j==1:
      sub_data = sub_texts
    if sub_data.shape[0] > 0:
      ##First date: take it from subject's identifiers file (first file if there are multiple)
      identifier_Files = os.listdir(data_filepath + "/" + patient_name +  "/identifiers")
      identifiers = pd.read_csv(data_filepath + "/" + patient_name +  "/identifiers/"+ identifier_Files[0], sep = ",")
      firstDate = identifiers["UTC time"]
      from_zone = tz.gettz('UTC')
      to_zone = tz.gettz('America/New_York')
      UTC = datetime.strptime(firstDate[0], '%Y-%m-%dT%H:%M:%S.%f') 
      EST = UTC.replace(tzinfo=from_zone).astimezone(to_zone)
      firstDate = EST.date()
      
      ##Last date: look at all the subject's directories (except survey) and find the latest datefor each directory
      directories = os.listdir(data_filepath + "/" + patient_name)
      directories = list(set(directories)-set(["survey_answers","survey_timings"]))
      lastDate = []
      
      for i in directories:
        files = os.listdir(data_filepath + "/" + patient_name + "/" + i)
        lastDate.append(files[-1])
      
      ##Converting dates to EST time zone
      from_zone = tz.gettz('UTC')
      to_zone = tz.gettz('America/New_York')
      UTC = [datetime.strptime(i, '%Y-%m-%d %H_%M_%S.csv') for i in lastDate]
      EST = [i.replace(tzinfo=from_zone).astimezone(to_zone) for i in UTC]
      date_list = [i.date() for i in EST]
      
      ##Get the latest date among all the directories
      lastDate = max(date_list)  
      
      ##Add zeroes for dates within the range but not in sub_data
      datesInRange = pd.date_range(start = firstDate, end = lastDate).tolist()
      complete_data = pd.DataFrame({"id":patient_name,"date":datesInRange})
      complete_data['date'] = complete_data['date'].astype(str)
      sub_data['date'] = sub_data['date'].astype(str)
      complete_data = complete_data.merge(sub_data,how='outer',on = ["id","date"]).fillna(0.0)
      
    if j==0:
      data1 = complete_data
    if j==1:
      data2 = complete_data
      data2 = data2.drop(["id","date"], axis=1)
      temp = pd.concat([data1,data2],axis=1)
      final_output = final_output.append(temp)

C:\Users\glius\Anaconda3\lib\site-packages\ipykernel_launcher.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [238]:
final_output.shape

(2602, 22)

In [236]:
final_output.head(10)

,id,date,num of in calls,num of missed calls,num of out calls,num of in phones,num of missed phones,num of out phones,total len of in calls,total len of missed calls,...,mean len of missed calls,mean len of out calls,num of received sms,num of sent sms,num of received phone,num of sent phone,total len of received sms,total len of sent sms,mean len of received sms,mean len of sent sms
0,1s5wlcm6,2018-01-19,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1s5wlcm6,2018-01-20,0.0,0.0,5.0,0.0,0.0,3.0,0.00,0.0,...,0.0,2.106667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1s5wlcm6,2018-01-21,1.0,0.0,0.0,1.0,0.0,0.0,0.15,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1s5wlcm6,2018-01-22,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1s5wlcm6,2018-01-23,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1s5wlcm6,2018-01-24,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1s5wlcm6,2018-01-25,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1s5wlcm6,2018-01-26,1.0,0.0,0.0,1.0,0.0,0.0,0.55,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1s5wlcm6,2018-01-27,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1s5wlcm6,2018-01-28,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0